global:
  env: default

default:
  replicas: 1

deployment_image:
  repository: 465967067450.dkr.ecr.us-east-1.amazonaws.com/test
  tag: grafana
  pullPolicy: IfNotPresent
  image_secret_name: ecr-registry

initContainers:
  repository: 465967067450.dkr.ecr.us-east-1.amazonaws.com/test
  tag: k8s-sidecar
  pullPolicy: IfNotPresent
  image_secret_name: ecr-registry
   
